### PR TITLE
Decode html characters

### PR DESCRIPTION
**Pull request by eneiluj**
When a placeholder contains characters like `' " < >`, they are replaced by their HTML code. This leads to this kind of issues:
Fix https://github.com/nextcloud/server/issues/26113

Would it be a good solution to decode them here?

### CODE REVIEW

**Review by ChristophWurst — CHANGES_REQUESTED** [review]
sounds like a bad idea. you can achieve the same with `options.sanitize=false`

**Comment by eneiluj** [comment]
@ChristophWurst Thanks, that's what I was looking for.

Do you mean on some `translate` and `translatePlural` calls, when we know those characters are potentially there?
Or do you mean adding this option here in `translate` and `translatePlural` definitions?

I tried it but I'm still getting the HTML char codes for placeholders substitutions.
``` javascript
t('app', 'Hello {name}', { name: 'O\'Brian' }, {}, null, { sanitize: false })
```
returns `Hello O&#39;Brian`

**Comment by ChristophWurst** [comment]
> I tried it but I'm still getting the HTML char codes for placeholders substitutions.
> 
> ```js
> t('app', 'Hello {name}', { name: 'O\'Brian' }, {}, null, { sanitize: false })
> ```

There is also `options.escape`

**Comment by eneiluj** [comment]
``` javascript
t('app', 'Hello {name}', { name: 'O\'Brian' }, {}, null, { sanitize: false, escape: false })
```
still returns `Hello O&#39;Brian` :thinking:

**Comment by skjnldsv** [comment]
> still returns `Hello O&#39;Brian`

Make sure you're properly using the method from `@nextcloud/l10`n and not `window.t` :thinking:

**Comment by szaimen** [comment]
Any update here?

**Comment by eneiluj** [comment]
@skjnldsv @ChristophWurst Using `@nextcloud/l10n@^1.4.1`:
``` javascript
import { translate } from '@nextcloud/l10n'
console.debug(translate('app', 'Hello {name}', { name: 'O\'Brian' }, {}, null, { sanitize: false, escape: false }))
// => Hello O&#39;Brian
console.debug(window.t('app', 'Hello {name}', { name: 'O\'Brian' }, {}, null, { sanitize: false, escape: false }))
// => Hello O&#39;Brian
```

**Comment by eneiluj** [comment]
Sorry for the noise. There are too many parameters passed in the examples I gave. All good.

**Comment by szaimen** [comment]
@eneiluj will https://github.com/nextcloud/server/issues/26113 not be fixed then?

**Comment by eneiluj** [comment]
@szaimen Yes, thanks for reminding me: https://github.com/nextcloud/server/pull/27912

**Pull request closed without merging**
